# Generated by Django 3.1.3 on 2020-11-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('text_post', models.TextField(verbose_name='Текст статьи')),
                ('data_post', models.DateTimeField(max_length=10, verbose_name='Дата')),
            ],
        ),
    ]
